PACKAGE_DIR_LOX=com/craftinginterpreters/lox
PACKAGE_DIR_TOOL=com/craftinginterpreters/tool

all:
	-@ javac -cp $(PACKAGE_DIR_LOX)/ $(PACKAGE_DIR_LOX)/*.java
	-@ javac -cp $(PACKAGE_DIR_TOOL)/ $(PACKAGE_DIR_TOOL)/*.java
